#!/bin/bash -x
# My first script

# Download composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

#create laravel project 
php composer.phar create-project laravel/laravel webapp

#delete composer.phar
rm composer.phar


#copy source files in source-webapp into webapp
cp -rT  ./source-webapp ./webapp

#migrate database again
php ./webapp/artisan migrate:refresh

#copy python scripts
cp -rT ./python-scripts ./webapp/scripts


#Change owner for files needs to be modified by the app
sudo chown -R www-data:www-data ./webapp/storage
sudo chown  www-data:www-data ./webapp/database
sudo chown  www-data:www-data ./webapp/database/database.sqlite
